version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn -v

workflows:
  welcome:
    jobs:
      - install-node-example
