version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-npm: false
          install-yarn: true
          node-version: 12.20.0
          yarn-version: 1.22.4
      - run: node --version
      - run: yarn -v

workflows:
  install-yarn:
    jobs:
      - install-node-example
