version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.20'
          yarn-version: '1.22.19'
      - run: node --version
      - run: yarn -v

workflows:
  install-yarn:
    jobs:
      - install-node-example
