name: Trigger
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger another!"

  git-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/git/refs/heads/push-test \
          -f sha=$(git rev-parse origin/main) \
          -F force=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
