# after completed `Triggered by another` workflow will be called
name: Trigger

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger another!"

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my-word: 'Open Sesame'
