name: 'Auto Assign'
on: [pull_request]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
    # - uses: toshimaru/auto-assign-action@skip-draft-option
    - uses: toshimaru/auto-author-assign@add-assign-action
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
