name: 'Auto Assign'
on: [pull_request]
jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.head_ref }}
    - uses: toshimaru/auto-author-assign@v1.4.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
