name: 'Auto Assign'
on: [pull_request]
jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
    - uses: toshimaru/auto-author-assign@v1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
