name: 'Auto Assign'
on: [pull_request]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
    - uses: toshimaru/auto-assign-action@skip-draft-option
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
