name: 'Auto Assign'

on:
  issues:
    types: [ opened, reopened ]
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
    - uses: toshimaru/auto-author-assign@v2.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
