name: Delete Action Cache (test)
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/delete-action-cache@main
