on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300
  main:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - run: sleep 300
