name: "Continue on error"
on:
  pull_request:
jobs:
  continue-on-error:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step will run"
      - run: exit 1
        continue-on-error: true
      - run: echo "This step will not run"
