name: Delete Unused Caches
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/heads/${{ github.head_ref }}
