name: Delete Action Cache
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * 1'
jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/delete-action-cache@main
