name: 'Check Docker Versions'
on: [workflow_dispatch]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - run: docker -v
      - run: docker-compose -v
      - run: echo 'Hello from workflow_dispatch'
