name: 'Label Actions'

on:
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/label-actions@v1.3.0-3
        with:
          github-token: ${{ github.token }}
          process-only: 'prs'
