name: 'Label Actions'

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: toshimaru/label-to-actions@v1
        with:
          github-token: ${{ github.token }}
