name: PR Number
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Number
        id: pr-number
        uses: actions/github-script@v8
        with:
          script: |
            return context.issue.number;
      - run: |
          echo "PR number: ${{ steps.pr-number.outputs.result }}"
