name: PR Number
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Number
        id: pr-number
        uses: actions/github-script@v7
        with:
          script: |
            if (github.event_name === 'issue_comment') {
              return context.issue.number;
            } else if (github.event_name === 'pull_request') {
              return github.event.number;
            } else {
              throw Error('Unexpected event');
            }
      - run: |
          echo "PR number: ${{ steps.pr-number.outputs.result }}"
