name: Reusable workflow example

on:
  workflow_call:
    inputs:
      my-word:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      # head_ref is empty
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ inputs.my-word }}
