name: Reusable workflow

on:
  workflow_call:
    inputs:
      my-word:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      # head_ref is empty
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ inputs.my-word }}
