name: Reusable workflow example

on:
  workflow_call:
    inputs:
      my-word:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.my-word }}
