name: RuboCop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: |
        bundle update --bundler
        bundle install
    - name: Run RuboCop
      run: bundle exec rubocop
