name: Setup Ruby
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rspec:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
